/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrowTop: typeof import('./src/components/icons/ArrowTop.vue')['default']
    HtmlVideo: typeof import('./src/components/cvele-components/html-video/index.vue')['default']
    Lightbox: typeof import('./src/components/cvele-components/Lightbox.vue')['default']
    Marquee: typeof import('./src/components/cvele-components/Marquee.vue')['default']
    MarqueeWrapper: typeof import('./src/components/MarqueeWrapper/index.vue')['default']
    PageFooter: typeof import('./src/components/global/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/cvele-components/PageHeader.vue')['default']
    Parallax: typeof import('./src/components/cvele-components/parallax/index.vue')['default']
    Picture: typeof import('./src/components/cvele-components/Picture.vue')['default']
    Plus: typeof import('./src/components/cvele-components/Plus.vue')['default']
    Popup: typeof import('./src/components/global/Popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./src/components/cvele-components/Spinner.vue')['default']
    TextBox: typeof import('./src/components/global/TextBox.vue')['default']
    TransitionGsap: typeof import('./src/components/cvele-components/TransitionGsap.vue')['default']
    WorkBox: typeof import('./src/components/global/WorkBox.vue')['default']
    WorkExperience: typeof import('./src/components/WorkExperience/index.vue')['default']
    Works: typeof import('./src/components/Works/index.vue')['default']
  }
}
